export const accesorize = {
    backgrounds: {
        blue50: '#5596f6',
        blue60: '#2a7bf4',
        blue70: '#2a5ca7',
        green60: '#74bd29',
        green70: '#6a9440',
        grey40: '#cccccc',
        grey70: '#666666',
        grey80: '#333333',
        red50: '#e85e23',
        red60: '#cb4c15',
        red70: '#9f370a',
        yellow50: '#fcd33f',
        yellow60: '#e6b60d',
        yellow70: '#cf8e10',
    },
    ears: {
        default: 'default',
        'tilt-backward': 'tilt-backward',
        'tilt-forward': 'tilt-forward',
    },
    hair: {
        default: 'default',
        bang: 'bang',
        curls: 'curls',
        elegant: 'elegant',
        fancy: 'fancy',
        short: 'short',
    },
    neck: {
        default: 'default',
        'bend-backward': 'bend-backward',
        'bend-forward': 'bend-forward',
        thick: 'thick',
    },
    eyes: {
        default: 'default',
        angry: 'angry',
        naughty: 'naughty',
        panda: 'panda',
        smart: 'smart',
        star: 'star',
    },
    nose: {
        default: 'default',
    },
    mouth: {
        default: 'default',
        astonished: 'astonished',
        eating: 'eating',
        laugh: 'laugh',
        tongue: 'tongue',
    },
    leg: {
        default: 'default',
        cookie: 'cookie',
        'bubble-tea': 'bubble-tea',
        'game-console': 'game-console',
        'tilt-backward': 'tilt-backward',
        'tilt-forward': 'tilt-forward',
    },
    accessories: {
        earrings: 'earrings',
        flower: 'flower',
        glasses: 'glasses',
        headphone: 'headphone',
    },
}